AllCops:
  TargetRubyVersion: 2.2
  Exclude:
    - 'bin/**/*'
    - 'config/**/*'
    - 'db/**/*'
    - 'vendor/**/*'

Rails:
  Enabled: true

Documentation:
  Enabled: false

Metrics/LineLength:
  Exclude:
    - 'spec/spec_helper.rb'
