development: &default
  aws_access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
  aws_secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
  region: 'eu-west-1'
  s3_bucket: <%= ENV['S3_BUCKET'] %>

production:
  <<: *default
