development:
  adapter: postgresql
  encoding: unicode
  database: cfb-dev
  pool: 5
  username:
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: cfb-test
  pool: 5
  username:
  password:
