# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  aws_access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
  aws_secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
  aws_region:  <%= ENV['AWS_REGION'] %>
  aws_bucket: <%= ENV['AWS_BUCKET'] %>
  secret_key_base: 3da16798058b179f5fdbf9e8e7e3943a5f0b1c5197626a56e9dc36c6cf3ce17373d6705b118cab2f6ccc2ac0596c9d60c7e7cfd83c20f4fdb09e7d30cebd1993

test:
  secret_key_base: c0a3dff2f93aa0810cf16f6f4b68246a51c421f9ae886d3a922889eaa577c479ed95b5c29de22c7ebe0140166b3b1e25a1ba2f951d52e0f2a2f1742fede261d9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  aws_access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
  aws_secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
  aws_region:  <%= ENV['AWS_REGION'] %>
  aws_bucket: <%= ENV['AWS_BUCKET'] %>
  host: <%= ENV["HOST"] %>
  raygun_api_key: <%= ENV["RAYGUN_API_KEY"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  smtp_address: <%= ENV["SMTP_ADDRESS"] %>
  smtp_user_name: <%= ENV["SMTP_USER_NAME"] %>
  smtp_password: <%= ENV["SMTP_PASSWORD"] %>
